package com.assignment.retailstore.service;

public interface IDiscountService {
    /**
     * @param userId     user id of a customer
     * @param billAmount amount of the bill generated by system without discount
     * @return net payable amount after applying discount
     */
    double calculateDiscount(Long userId, double billAmount);
}
